### ISSUE TITLE
ebay-font has issues with Marko 5

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebay-font#47]
Marko version: `marko@5.0.0-next.45`

It throws the following error:-

```
uncaughtException Unexpected token '<'
node_modules/ebay-font/font/marketsans/template.marko:1
<style nonce=data.nonce>
^

SyntaxError: Unexpected token '<'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:873:16)
    at Function._load (/app/node_modules/brogan-ebay/index.js:37:53)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/ebay-font/font/marketsans/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:873:16)
    at Function._load (/app/node_modules/brogan-ebay/index.js:37:53)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
```

**Comment by PrashantAshok** [comment]
Changing `renderer` to `template` fixes this problem.
